### ISSUE TITLE
HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by Arktius** [docker/distribution-library-image#103]
When I push my application to a private registry in my own namespace, I get the following error:

```
...\Docker>docker push registry.../namespace/application
6e7b8eefdb11: Pushing [==================================================>]  185.3kB
31f8d07a1a5e: Layer already exists
db0abfd144ab: Pushing [==================================================>]  116.7kB
bc693526588f: Layer already exists
38d7ba77fba6: Pushing [>                                                  ]    535kB/5.148GB
fcd8d39597dd: Layer already exists
875120aa853c: Layer already exists
f2cb0ecef392: Layer already exists
received unexpected HTTP status: 500 Internal Server Error
```
What I've tried so far:

Add ` "allow-nondistributable-artifacts": [
        "localhost:5000"
    ]
` to the settings (Docker Engine).

Restart the computer as well as Docker.

Docker logout and login again.

I don't know what could have changed. The application works flawlessly on my local machine and I got no errors a week before. The Docker file is unchanged. 

How can I get more information about the failed push?

Docker version 19.03.8
Kubernetes 1.15.5

**Comment by AndreasHassing** [comment]
It looks like you're using Docker for Windows, which means you most likely are trying to push a Windows image to the registry. If so, see #89.

**Comment by Arktius** [comment]
The server was actually down. =)
