### ISSUE TITLE
htpasswd not in latest image

### ISSUE THREAD

**Issue by snelson3** [docker/distribution-library-image#107]
According to the documentation at https://docs.docker.com/registry/deploying/, the following command should be used to get a password for basic auth.

_docker run --entrypoint htpasswd registry:2 -Bbn testuser testpassword > auth/htpasswd_

This worked last week, but I have since pulled the newest version of registry:2 and now running the above command gives

_docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"htpasswd\": executable file not found in $PATH": unknown._

**Comment by gblewis1** [comment]
I saw this issue also and worked around it for now by pinning to registry:2.7.0

**Comment by donghoang89** [comment]
I'm experience the same issue on the latest registry:2 image

**Comment by maelfosso** [comment]
I was about to create an issue for that.
I got a similar issue

**Comment by rgl** [comment]
This worked with 2.7.1 too. This means the 2.7.1 tag is being changed in incompatible ways. Why is that happening? Shouldn't 2.7.1 be the same forever? Or should we anchor the version with a sha (which I think is pretty bad because the sha is very opaque)?

**Comment by tianon** [comment]
Using the digest is a bit opaque, yes, but if you want an image that will definitely not ever change, that's exactly what the content addressable digest is designed for.

**Comment by rgl** [comment]
I could argue that using a content addressable digest is for something else (e.g. tooling/security) and not really for human usage/communication like a tag is.

Do you known what is preventing docker hub from removing/garbage-collecting images/layers that are not referenced by any tag? Or is docker hub always inflating?

**Comment by tmurakam** [comment]
It seems that the commit 4e5a501 removes apache2-utils so htpasswd does not exist. It should be fixed and add apache2-utils.

**Comment by fei922** [comment]
Why is htpasswd deleted in version 2.7.1, will there be any in the future?

**Comment by eigood** [comment]
Removing a package(apache2-utils) is a security fix?  That seems like a rather curious assumption.  Isn't there a fixed version for whatever "security" problem was being dealt with, and that keeping the package installed/available, but upgrading to the fixed version, is the safer approach?  Removing features with a minor version bump is *not* how semver is supposed to be honored.

**Comment by goldfingyr** [comment]
You could just enter the password directly from the host side. Of course that would mean your host to have apache2-utils installed. But in that case it is just:
htpasswd -Bb <path-to-passwordfile> <username> <password>
Which will work with the later containers.
This is a work-around. Htpasswd should be in the container.

**Comment by douglasjreynolds** [comment]
@goldfingyr This doesn't work in 2.7.1.  The htpasswd functionality was removed from the registry application.  This might be because the library wasn't linked since it wasn't not in the container.

If this functionality was removed from the container, it needs to be removed from the documentation as well.  https://docs.docker.com/registry/deploying/

**Comment by stefanloerwald** [comment]
This is absurd. This is a breaking change in a non-major update. At the very least, the documentation should be updated.

To anyone running into the same issue: Just avoid the `registry` image and use `httpd` instead:

```
docker run --rm --entrypoint htpasswd httpd:2 -Bbn yourUserName yourPassword
```
