### ISSUE TITLE
AWS S3 storage driver support for IMDSv2

### ISSUE THREAD

**Issue by zully** [docker/distribution-library-image#121]
Using registry:2.7.1 It does not appear that the S3 storage driver supports the assuming of an IAM role when the Instance Metadata Service V2 is enabled on an EC2 instance in AWS.  Turning on IMDSv2 results in this error in the log when attempting to push an image to the registry when using the S3 storage driver.

_level=error msg="response completed with error" err.code=unknown err.detail="s3aws: NoCredentialProviders: no valid providers in chain. Deprecated._

This can be replicated by turning on/off IMDSv2 on the EC2 instance hosting the container:
`aws ec2 modify-instance-metadata-options --instance-id <INSTANCE_ID> --http-token <required|optional> --http-endpoint enabled --http-put-response-hop-limit 2  --region <REGION>`

Manually exec'ing into the container and executing the v2 curl commands to the metadata service succeed, as well as using the aws-cli container from the same instance:

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html

Turning off IMDSv2 and re-attempting a push of an image succeeds.

IMDSv2 Information:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

Looks like IMDSv2 support was added in aws-sdk-go 1.25.38
https://github.com/aws/aws-sdk-go/releases/tag/v1.25.38

**Comment by milosgajdos** [comment]
This is not the right repository to open this issue on. All issues related to distribution implementation should be opened on the distribution repository.
