### ISSUE TITLE
How many times HealthCheck will restart container ? Infinite time unless becomes healthy or once twice ? 

### ISSUE THREAD

**Issue by vandanpathak-gep** [docker/distribution-library-image#136]
How many times HealthCheck will restart container ? Infinite time unless becomes healthy or once twice ?

**Comment by milosgajdos** [comment]
This is a wrong repo to ask this question, I'm afraid.
if you are asking about compose healthcheck please ask in the docker-compose repo
If you are asking about kubernetes healthcheck please ask there. 
This repo is only used for building the distribution image
