### ISSUE TITLE
Cannot push/pull images with local registry

### ISSUE THREAD

**Issue by jbasb** [docker/distribution-library-image#139]
I followed the instructions found here: https://hub.docker.com/_/registry
```
$ docker run -d -p 5000:5000 --restart always --name registry registry:2
$ docker pull ubuntu
$ docker tag ubuntu localhost:5000/ubuntu
$ docker push localhost:5000/ubuntu
```

Attempts to push or pull images time out with the following errors:
For docker push: 

> Get "http://localhost:5000/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

For docker pull: 

> Error response from daemon: Get "http://localhost:5000/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Does anyone have pointers on how to troubleshoot this?

This was done on a VM running Linux Mint if that helps.

**Comment by milosgajdos** [comment]
Very strange everything works fine on my machine:

```shell
$ docker push localhost:5000/registry:2
The push refers to repository [localhost:5000/registry]
a1d94f4a4c89: Pushed
1d80677cd085: Pushed
58548fced558: Pushed
79f02b258438: Pushed
24302eb7d908: Pushed
2: digest: sha256:affdb68e24c93262ee98a5bdc371e8f631568e9b4401375e7a0ecc705ac526b2 size: 1363
```

@jbasb can you please open an issue in https://github.com/distribution/distribution, more importantly, please use the latest available tag -- version 2 is ancient.

**Comment by jbasb** [comment]
I'm getting the same issue even with the latest tag.
