### ISSUE TITLE
Bug in Registry API/Registry DELETE corrupts data store

### ISSUE THREAD

**Issue by bigtfromaz** [docker/distribution-library-image#140]
I discovered an issue that needs to be addressed related to the Open-Source Registry and its implementation of the Docker Registry API v2. 

I am prepping to develop an open-source package primarily to list and remove tags and images. It'll be tool for use when a repository admin no longer wants to offer certain images and tags to registry consumers.  I ran into an issue while prototyping my intended HTTP conversations in Postman.

In this case I pulled hello-world:latest, created a few tags and pushed them to my sandbox registry using docker. Using the API, I deleted an image using an HTTP DELETE referencing the image's Docker-Content-Digest. The delete ran successfully but the repository is still listed in _catalog. There are no tags or blobs associated with it. This seemed to me like the HTTP DELETE action logically corrupted the registry datastore by failing to delete all the image's metadata.

I decided to see what Docker would do when it encountered the errant construct. I issued a command any developer might use if they didn't know the image was deleted:

> docker pull https://myhost.net/hello-world-old:latest

It returned this message:

       `Error response from daemon: manifest for myhost.net/hello-world-old:latest not found: 
         manifest unknown: manifest unknown` 
**_This message indicates a corrupt registry datastore because the response should be NOT FOUND._**

A utility like this API should never corrupt persistent storage.  In my opinion, remediating this should be a high priority. 

We have tabled our use of the Open-Source Registry because it isn't ready for us to rely on it for our devops pipelines. It's disappointing because we will need three docker instances on three servers. With the registry, we would merely add some containers to our cluster.  

Before anyone asks, I tried triggering garbage collection. It made no difference. In any event, you should be able to push an image, delete it, and get a 404 trying to pull it; in sequence without waiting for garbage collection.

**Comment by milosgajdos** [comment]
Can you please open an issue in https://github.com/distribution/distribution and list what version/tag of the registry image you used for your experiments?

**Comment by bigtfromaz** [comment]
@milosgajdos Done: [https://github.com/distribution/distribution/issues/3695](https://github.com/distribution/distribution/issues/3695)
