### ISSUE TITLE
Does proxy work on unavailable upstream?

### ISSUE THREAD

**Issue by Felixoid** [docker/distribution-library-image#141]
Hello. According to [manual](https://github.com/docker/docker.github.io/blob/master/registry/recipes/mirror.md#what-if-the-content-changes-on-the-hub), the registry mirror requests if the images updated on the ustream.

We use docker very intensively in our CI, and quite often affected by issues like this:

```
Exception: Command ['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_cleanup_dir_after_bad_zk_conn/_instances_0/.env', '--project-name', 'roottestcleanupdirafterbadzkconn', '--file', '/ClickHouse/tests/integration/test_cleanup_dir_after_bad_zk_conn/_instances_0/node1/docker-compose.yml', '--file', '/compose/docker_compose_keeper.yml', 'pull'] return non-zero code 1: Pulling zoo2  ... 
Pulling zoo3  ... 
Pulling zoo1  ... 
Pulling node1 ... 
Pulling zoo3  ... error
Pulling zoo1  ... error
Pulling zoo2  ... error
Pulling node1 ... error

ERROR: for zoo3  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

ERROR: for zoo1  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

ERROR: for zoo2  Get "https://registry-1.docker.io/v2/": context deadline exceeded

ERROR: for node1  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Get "https://registry-1.docker.io/v2/": context deadline exceeded
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

And then a huge number of jobs fail.

Do I understand correctly, that `registry:2` can't be setup to serve requests with what it has w/o failing?

**Comment by milosgajdos** [comment]
Hi, this is the wrong repository to report this Can you please open an issue in https://github.com/distribution/distribution.
Also, please use either the latest available tag (`2` is ancient) or `edge` tag (built off `main`).
Closing

**Comment by Felixoid** [comment]
Thank you, I will.. just a note, that according to https://hub.docker.com/_/registry?tab=tags [2](https://hub.docker.com/layers/registry/library/registry/2/images/sha256-6f86956ed3802764cf98f5f20ed549a649ffd1f24fb273aef48748da5531b576?context=explore) is the same as [latest](https://hub.docker.com/layers/registry/library/registry/latest/images/sha256-6f86956ed3802764cf98f5f20ed549a649ffd1f24fb273aef48748da5531b576?context=explore)

**Comment by Felixoid** [comment]
I guess it's the general strategy for docker hub. At least, it looks very organic to me that latest == 2 == 2.8 == 2.8.1

**Comment by milosgajdos** [comment]
> I guess it's the general strategy for docker hub. 

Note that `distribution` is no longer owned by Docker. It was donated to CNCF
