### ISSUE TITLE
Docker Registry issue when I use NGINX Reverse Proxy

### ISSUE THREAD

**Issue by patchint** [docker/distribution-library-image#142]
I get some issues while I'm trying to get my images on my Docker Registry.

I've got some issues while trying to make a reverse proxy on NGINX to use registry, I was trying to make basic auth on it.

Now, I get a second issue : (That's when I'm trying to use my own registry)

![image](https://user-images.githubusercontent.com/55617813/187268502-44b6f279-0eaf-46ae-a8f8-1169b0050044.png)

My NGINX configuration : 

```
server {
	listen 8443 http3;
	listen [::]:8443 http3;

	listen 8443 http2 ssl;
	listen [::]:8443 http2 ssl;

	server_name SERVER;

	access_log /var/log/nginx/SERVER/access.log;
	error_log /var/log/nginx/SERVER/error.log;

	ssl_certificate /etc/nginx/ssl/SERVER_ecc/fullchain.cer;
	ssl_certificate_key /etc/nginx/ssl/SERVER_ecc/SERVER.key;
	ssl_stapling_file /etc/nginx/ocsp_staple/SERVER_ecc.der;

	include includes/custom_error_pages.conf;
	include includes/common_headers.conf;
	include includes/HSTS-preload.conf;

	set $upstream 192.168.1.46:5000;

	location / {
		proxy_pass http://$upstream/;
		proxy_hide_header X-Powered-By;
		auth_basic "Restricted Content";
                auth_basic_user_file sites/.htpasswd;
	}
}

server {
	listen 8080;
	listen [::]:8080;
	server_name SERVER;
	return 301 https://$server_name$request_uri;
}
```

**Comment by milosgajdos** [comment]
Can you please open an issue in https://github.com/distribution/distribution

This repository is only for image-related issues, not distribution/proxy implementation.

Thanks
