### ISSUE TITLE
HTTP 413

### ISSUE THREAD

**Issue by basavarajbhavi** [docker/distribution-library-image#143]
error parsing HTTP 413 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.21.6</center>\r\n</body>\r\n</html>\r\n"

**Comment by milosgajdos** [comment]
Closing. Not enough context and wrong repository.
