### ISSUE TITLE
Run Docker registry in kubernetes using SSL certificates

### ISSUE THREAD

**Issue by OfficialVreesie** [docker/distribution-library-image#145]
I have a problem. I am trying to run a private docker registry on my server in kubernetes. To do this, I am using Ingress-Nginx with a LetsEncrypt issuer. I have setup the Ingress resource and the LetsEncrypt issuer has succesfully obtained a certificate. After that I ran the following 3 commands:

    kubectl get secret project-docker-tls -n project-utility \
      -o jsonpath='{.data.tls\.crt}' | base64 --decode > /mnt/data/project/docker-registry/certs/tls.crt
    
    kubectl get secret project-docker-tls -n project-utility \
      -o jsonpath='{.data.tls\.key}' | base64 --decode > /mnt/data/project/docker-registry/certs/tls.key
    
    kubectl create secret generic docker-registry-certs \
      --from-file=tls.crt=/mnt/data/project/docker-registry/certs/tls.crt \
      --from-file=tls.key=/mnt/data/project/docker-registry/certs/tls.key \
      --namespace project-utility

This creates a secret using the obtained certificate so that I can use that in my private docker registry deployment. The deployment has the following config:

    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: private-docker-registry
      namespace: project-utility
      labels:
        app: private-docker-registry
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: private-docker-registry
      template:
        metadata:
          labels:
            app: private-docker-registry
        spec:
          containers:
          - image: registry:2
            name: private-docker-registry
            imagePullPolicy: IfNotPresent
            ports:
            - name: docker
              containerPort: 443
            env:
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:443
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
            volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-dir
            - mountPath: /certs
              name: registry-certs
              readOnly: true
          volumes:
          - name: registry-dir
            hostPath:
              path: /mnt/data/project/docker-registry/images
          - name: registry-certs
            secret:
              secretName: docker-registry-certs

Now I would expected that when I deploy this the docker registry would be live under https, but when I try to reach the site, I get a HTTP ERROR 400. Using Postman I get to see more of the issue: `Client sent an HTTP request to an HTTPS server.`. Why is this registry still not running in https. I am forwarding the Ingress traffic over port 443, then my service will forward the same traffic to the deployment-app, with both `port` and `targetPort` set to 443.

I did go into the pod using SSH and checked if the certs where actually there, and they are! This cluster runs behind a reverse proxy which also has letsencrypt certficiates on a different server. That server redirects all traffic to the server where I am running my cluster on. This means that there are 2 sets of certificates, but I have never had problems with this setup and all my other domains are SSL secured correctly!

What am I missing here?

**Comment by milosgajdos** [comment]
I _suspect_ registry process is somehow ignoring the TLS ENV vars hence not picking up the certs. Can you please move this conversation to https://github.com/distribution/distribution.

This repository is only about the build source of the official image. Thanks. Closing this issue.
