### ISSUE TITLE
Issues on using the registry image for mirroring

### ISSUE THREAD

**Issue by wu105** [docker/distribution-library-image#16]
Tried to setup a mirror registry and run into the following issues:

- the mirror feature is fantastic but getting it to work takes some doing.  Finding https://github.com/docker/distribution/blob/master/docs/mirror.md took a number of hops on the internet, which indicated that a configuration file inside the container should be modified.  It would be more desirable to have a run time environment variable to achieve the same effect given the effort involved with modifying a configuration file within a container.  In addition, the docker daemon also needs the proxy information, thus it is possible for the daemon to pass such information and eliminating a second copy inside of the registry container.

- the Dockerfile for the registry at https://github.com/docker/distribution-library-image/blob/5cbbc8d1e6046cef5938e3380fd2a5fbd854f921/Dockerfile probably is a good place to expose the configuration files (e.g., comments and volumes) and environment variables but it currently have none.

**Comment by zas** [comment]
https://github.com/docker/distribution/blob/master/docs/mirror.md is now a 404

I'm trying to set up such mirror registry, and i can't get it to work.

**Comment by dmp42** [comment]
cc @docker/docs-maintainers

**Comment by johndmulhausen** [comment]
@zas @wu105 The docs got migrated to docker/docker.github.io

I think you're looking for: https://github.com/docker/docker.github.io/blob/master/registry/recipes/mirror.md

Or:
https://docs.docker.com/registry/recipes/mirror/

**Comment by dmp42** [comment]
@wu105 I believe you *can* use environment variables to specify configuration instead of having to mount a configuration file.
The doc is here: https://docs.docker.com/registry/configuration/

(I haven't tested mirroring on that though)

**Comment by dmp42** [comment]
Closing for bookkeeping.

@wu105 if you still have trouble setting up mirroring using env vars, reaching out on irc or the forums is probably the fastest way to get help.
