### ISSUE TITLE
Run a private registry from the official image without a config file using S3

### ISSUE THREAD

**Issue by CameronGo** [docker/distribution-library-image#19]
I am currently running a v1 registry and am looking to migrate to the v2.  I've read through all the documentation, in particular this portion:

> NOTE: It is highly recommended to create a base configuration file with which environment variables can be used to tweak individual values. Overriding configuration sections with environment variables is not recommended.

Ideally; however, I would like to run the v2 registry with S3 as my persistent storage and without having to create my own custom registry image.  The reason for this thinking is, if I create a custom image based on the official image, then I have to store my image in my registry (the one I'm attempting to define with the image), which creates a circular dependence that makes me uncomfortable.  If my registry is down for some reason I may no longer be able to re-publish a fixed image and get it back up and running.

This would seem to indicate I need to run the registry and be able to define the configuration exclusively with the ENV variables (the way I had with v1).  When I try to do this; however, it fails to launch b/c the config example that is used by default already contains a local storage driver, so it throws an error.

Is there any way for me to run the official image and specify an S3 storage location without creating my own custom image?

**Comment by dennisxrow** [comment]
You could try this, it works for me:
```
docker run \
         -e REGISTRY_STORAGE=s3 \
         -e REGISTRY_STORAGE_S3_ACCESSKEY=myaccesskey \
         -e REGISTRY_STORAGE_S3_SECRETKEY=mysecretkey \
         -e REGISTRY_STORAGE_S3_REGION=eu-central-1 \
         -e REGISTRY_STORAGE_S3_BUCKET=my-docker-bucket \
         -e REGISTRY_STORAGE_S3_ENCRYPT=true \
         -e REGISTRY_STORAGE_S3_SECURE=true \
         -e REGISTRY_STORAGE_S3_V4AUTH=true \
         -e REGISTRY_STORAGE_S3_CHUNKSIZE=5242880 \
         -e REGISTRY_HTTP_SECRET=superdupersecret \
         -p 5000:5000 \
         registry
```
However I'm not sure if this is the recommended way.

**Comment by CameronGo** [comment]
Since I'm running in AWS I ended up just using the AWS ECS Registry instead.  That is working really well and then I have an auth mechanism that is handled for me too.  Thanks though.

**Comment by dmp42** [comment]
Closing this since @dennisxrow answer is actually answering the question (thanks!).
