### ISSUE TITLE
problem of curl registry/v2/_catalog?n=1000

### ISSUE THREAD

**Issue by cherry4477** [docker/distribution-library-image#21]
there is 504 error when curl registry/v2/_catalog?n=1000. and the response time is long,some time up to about 2 minutes

**Comment by dmp42** [comment]
Hi @cherry4477 

Recent work has enhanced the catalog performance: https://github.com/docker/distribution/pull/1895

Trying with registry >= 2.5.1 should help.

I'm closing since this ^ was merged, but please reopen on https://github.com/docker/distribution/ if you still have issues.
