### ISSUE TITLE
registry 2.5 doesn't seem save pushed repos to /registry

### ISSUE THREAD

**Issue by pcm32** [docker/distribution-library-image#23]
I just migrated a v1 registry to v2.5 on CoreOS. I used the following command to start the registry:

```bash
/usr/bin/docker run --name registry -e STORAGE_PATH=/registry -v /mnt/docker_registry_data/registry:/registry -e SEARCH_BACKEND=sqlalchemy -p 50000:5000 registry:2.5
```

however, nothing is being written to the  `/mnt/docker_registry_data/registry` directory on the host machine and upon inspection of the running container:

```bash
 docker exec -i -t registry sh

/ # ps -fea
PID   USER     TIME   COMMAND
    1 root       0:24 registry serve /etc/docker/registry/config.yml
   30 root       0:00 sh
   33 root       0:00 ps -fea
/ # cat /etc/docker/registry/config.yml 
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
/ # ls -l /var/lib/registry/docker/registry/v2/
total 16
drwxr-xr-x    3 root     root          4096 Aug  2 14:34 blobs
drwxr-xr-x    4 root     root          4096 Aug  2 14:39 repositories
/ # ls -l /registry/
total 0
```

you can notice that everything is being stored in `/var/lib/registry` which is an internal directory of the container. 

Am I doing something wrong? I essentially followed the instructions in the [docker-hub page](https://hub.docker.com/_/registry/). Thank you!

**Comment by pcm32** [comment]
Ok, I have found the answer, there seems to be newer documentation [here](https://docs.docker.com/registry/deploying/). In particular it says:

```
docker run -d -p 5000:5000 --restart=always --name registry \
-v `pwd`/data:/var/lib/registry \
  registry:2
```

**Comment by dmp42** [comment]
@pcm32 correct - the configuration syntax is not the same between v1 & v2
