### ISSUE TITLE
How to delete an image from the registry?

### ISSUE THREAD

**Issue by itshemant4u** [docker/distribution-library-image#27]
Please let me know if there is a way to delete an image from the registry.

**Comment by rgo** [comment]
You could try with this script https://github.com/burnettk/delete-docker-registry-image

Regards

**Comment by dmp42** [comment]
Also:

 * https://docs.docker.com/registry/spec/api/#/deleting-an-image
 * https://docs.docker.com/registry/spec/api/#deleting-a-layer

And: 

 * https://docs.docker.com/registry/garbage-collection/
