### ISSUE TITLE
Versions >0.9 Use Filesystem over Specified Engines

### ISSUE THREAD

**Issue by afrazkhan** [docker/distribution-library-image#29]
Running something like this (credentials vars are omitted since my instance has an instance profile in AWS):

```
docker run \
         --name=docker \
         -d \
         -e DEBUG=True \
         -e LOGLEVEL=debug \
         -e SETTINGS_FLAVOR=s3 \
         -e AWS_REGION="eu-west-1" \
         -e AWS_BUCKET=[BUCKET_NAME] \
         -e STORAGE_PATH=/registry \
         -e SEARCH_BACKEND=sqlalchemy \
         -p 5000:5000 \
         registry:2
```

should write data to the specified S3 bucket. Instead it writes to the filesystem `/var/lib/registry`. Overriding the storage engine with `REGISTRY_STORAGE_S3_BUCKET=[BUCKET_NAME]` tells me that 2 engines were specified in the config file.

Likely, that I can override this properly by mounting a complete config file, but according the docs, the point of the `SETTINGS_FLAVOR` variable seems to be to conveniently set up S3 storage without doing that.

**Comment by dmp42** [comment]
@afrazkhan I think the syntax you are using here is for the old, python, v1 registry.

`registry:2` has a different syntax: https://docs.docker.com/registry/configuration/ (and no "flavors")

**Comment by dmp42** [comment]
I'm closing this for book-keeping - if you still have issues, the fastest way to get help is probably on #irc or the forums.
