### ISSUE TITLE
Image was not pushed to S3

### ISSUE THREAD

**Issue by huajunzeng** [docker/distribution-library-image#31]
Hi, I use the latest (2.5.1) version of the image to create a registry server and use AWS S3 as the backend. However the image data is still saved under /var/lib/registry of the container. Nothing was uploaded to AWS S3. What might be the problem?

The run command as below:
```
sudo docker run \
         -e SETTINGS_FLAVOR=s3 \
         -e AWS_REGION=us-west-2 \
         -e AWS_BUCKET=my-docker \
         -e STORAGE_PATH=/registry \
         -e AWS_KEY=******** \
         -e AWS_SECRET=*********** \
         -e SEARCH_BACKEND=sqlalchemy \
         -e DEBUG=True \
         -p 5000:5000 \
         --name docker_registry \
         --restart=always \
         registry
```

**Comment by nikkon226** [comment]
It took me a while to figure this out too. I'm had to dig in, but found that this worked:

    docker_ service create --name registry -p 5000:5000 \
      -e REGISTRY_STORAGE_S3_BUCKET=******* \ 
      -e REGISTRY_STORAGE_S3_ROOTDIRECTORY=/registry \
      -e REGISTRY_STORAGE_S3_ACCESSKEY=******** \
      -e REGISTRY_STORAGE_S3_SECRETKEY=********* \
      -e REGISTRY_STORAGE_S3_REGION=us-east-1 \
      -e REGISTRY_STORAGE=s3 \
      registry:2.5.1

**Comment by huajunzeng** [comment]
It works! Thanks a lot @nikkon226 .

**Comment by jamshid** [comment]
The bad documentation is at https://hub.docker.com/_/registry/. If the env variable names have changed can the hub docs be updated?

**Comment by stevvooe** [comment]
That README is for the 0.9.1 registry, which was written in python. These docs need to be updated to use `registry:2`. It's probably time to also start having `registry:latest` point at 2.0.
