### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sergeyzwezdin** [docker/distribution-library-image#35]
**Description**

I've created docker registry and trying to make it work with StartSSL certificate. It works ok on Windows machines, but if I try to `docker login` from Linux it fails with `x509: certificate signed by unknown authority`.

**Steps to reproduce the issue:**
1. Have a clean Ubuntu 16.10 installation with installed docker
2. Get certificate for domain from StartSSL
3. Run docker registry from official image:
`docker run -d -p 443:5000 --restart=always --name registry -v /home/docker-host/.docker/:/certs -v /home/docker-host/.docker/auth/:/auth -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/docker.crt -e REGISTRY_HTTP_TLS_KEY=/certs/docker.key registry:2`
4. Try to `docker login <myhost>` from Windows
5. Try to `docker login <myhost>` from Linux

**Received results:**

On Windows it works fine and `Login Succeeded` message returned.

On Linux it returns `Error response from daemon: Get https://<myhost>/v1/users/: x509: certificate signed by unknown authority`

**Additional information you deem important (e.g. issue happens only occasionally):**

I also tried to `curl` registry URL from the same linux machine and it works fine, without certificate validation failures.

If I try to run `sudo dpkg-reconfigure ca-certificates` I see StartSSL's authority in the list.

Docker logs for registry container: 
```
time="2016-11-19T02:00:57Z" level=info msg="listening on [::]:5000, tls" go.version=go1.6.3 instance.id=5662e6ff-c481-4e30-9e8f-784c400366cc version=v2.5.1
2016/11/19 02:01:44 http: TLS handshake error from 192.168.1.18:37014: remote error: bad certificate
2016/11/19 02:01:44 http: TLS handshake error from 192.168.1.18:37016: remote error: bad certificate
2016/11/19 02:05:15 http: TLS handshake error from 192.168.1.18:37020: remote error: bad certificate
2016/11/19 02:05:15 http: TLS handshake error from 192.168.1.18:37022: remote error: bad certificate
```

I also tried to use `--insecure-registry` flag mentioned [here](https://github.com/docker/distribution/issues/1731), but it seems removed?

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-27-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 414.1 MiB
Name: docker-host
ID: 3ZU5:YEMB:FMJW:SVLC:HAD6:IBEB:WOOI:S4BV:HSIF:JHBH:PWTE:65GB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: docker-user
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by exdrunmeswt** [comment]
#28616 ×509:

**Comment by stevvooe** [comment]
Looks like the daemon does not trust the registry. Did you add the registry CA to docker certs?

**Comment by stevvooe** [comment]
Also, please open this issue in docker/docker or docker/distribution.

**Comment by adriano-fonseca** [comment]
I had this problem on the past trying run a docker-machine in virtualbox. I figure out that was 'the man of midle' in this case my proxy that signing every single package that it sends to me. Then I just provide the proxy certificate copying my proxy certificate to /var/lib/boot2docker/certs in docker-machine. However, I don't know how do the same To docker swarm. When I try to run swarm. I am having the follow error:

2017/01/18 22:16:21 Post https://discovery.hub.docker.com/v1/clusters: x509: certificate signed by unknown authority

There is a way to past my proxy certificate when I run the swarm node. I have tried to map my local cert with -v /home/docker-host/.docker/:/certs, but this didn't work.

**Comment by juanmiguelRuaDev** [comment]
I have the same problem.  I tried to change the certificated name from  
`/etc/docker/certs.d/registryname:5000/ca.crt` to`/etc/docker/certs.d/registryname:5000/domain.crt` but it didn't work

**Comment by rajasec** [comment]
same problem with 16.04.
x509: certificate signed by unknown authority

**Comment by FCA69** [comment]
Try and add your corp proxy's certificate both at OS and docker level.
Try and setup your "/etc/docker/certs.d/<domain>/" directory/files (for me it was necessary for "docker search" to work).
You may eventually specify which certificate location dockerd will use by adding a "tlscert" entry in your /etc/docker/daemon.json file. Use the one curl uses.
These 3 points solved the issue for me.

**Comment by rajasec** [comment]
Now added the corp proxy certificate in /etc/ssl and /etc/.. pki/anchors/  and it fixed the problem.

**Comment by ukreddy-erwin** [comment]
Any solution for the same problem in windows 10, Docker for windows??

![image](https://user-images.githubusercontent.com/21240709/54865184-9a876900-4d87-11e9-8baa-ba191f52c572.png)

**Comment by neerajtiwar** [comment]
> Try and add your corp proxy's certificate both at OS and docker level.
> Try and setup your "/etc/docker/certs.d//" directory/files (for me it was necessary for "docker search" to work).
> You may eventually specify which certificate location dockerd will use by adding a "tlscert" entry in your /etc/docker/daemon.json file. Use the one curl uses.
> These 3 points solved the issue for me.

it works!
