### ISSUE TITLE
can't use IAM role for a specific task in ECS

### ISSUE THREAD

**Issue by danielezer** [docker/distribution-library-image#71]
HI,
I am trying to deploy the docker registry as an ECS service with S3 storage. I am running my service inside an ECS cluster which has an IAM role. When I attach an IAM role to the ECS task with S3 permissions, I get s3aws: Access Denied when trying push an image. When I attach the IAM role to the EC2 machines in the ECS cluster, it works as expected.
I have seen this issue in the past with different applications and this usually happens because of an old aws sdk. in the newer versions of the SDK they can handle these kind of things - but in the older versions it doesn't work.

Thanks,
Daniel Ezer

**Comment by sopeters** [comment]
Having the same issue here - @danielezer how did yo solve it?
